### ISSUE TITLE
Try block around QRCodeScannerNode object creation

### ISSUE THREAD

**Issue by Philipp66904** [THI-Drone/qrcode_detection_package#6]
In line `430`:
```python
qr_code_scanner_node = QRCodeScannerNode(node_id)
``` 

Please add a try and except block around it and log the error message using a Ros logger (because otherwise the error message isn't logged).

Add the Ros log also to the other except block in the main function.

**Comment by finn-ehlers** [comment]
Thanks, added in newest commit
