### ISSUE TITLE
Use a mappable path for images.

### ISSUE THREAD

**Issue by J0las** [THI-Drone/qrcode_detection_package#7]
I would imagine an absolut path /images/timestamp from launch/no. of image.png for the images.
Maybe talk with @skrrpet about the path and what ros parameter to use for it.
And then integrate the mapping into the docker_run.sh file
https://github.com/THI-Drone/qrcode_detection_package/blob/761def5b93ffbbb0101e5e20900ff7b4d2d05875/qrcode_detection_package/main.py#L343

**Comment by Philipp66904** [comment]
fixed
